///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package account_history

import (
	"fmt"

	"github.com/xinliangnote/go-gin-api/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *AccountHistory {
	return new(AccountHistory)
}

func NewQueryBuilder() *accountHistoryQueryBuilder {
	return new(accountHistoryQueryBuilder)
}

func (t *AccountHistory) Create(db *gorm.DB) (id uint64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type accountHistoryQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *accountHistoryQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *accountHistoryQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&AccountHistory{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *accountHistoryQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&AccountHistory{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *accountHistoryQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&AccountHistory{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *accountHistoryQueryBuilder) First(db *gorm.DB) (*AccountHistory, error) {
	ret := &AccountHistory{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *accountHistoryQueryBuilder) QueryOne(db *gorm.DB) (*AccountHistory, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *accountHistoryQueryBuilder) QueryAll(db *gorm.DB) ([]*AccountHistory, error) {
	var ret []*AccountHistory
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *accountHistoryQueryBuilder) Limit(limit int) *accountHistoryQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *accountHistoryQueryBuilder) Offset(offset int) *accountHistoryQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereId(p mysql.Predicate, value uint64) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereIdIn(value []uint64) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereIdNotIn(value []uint64) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) OrderById(asc bool) *accountHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereAccountId(p mysql.Predicate, value uint64) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "account_id", p),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereAccountIdIn(value []uint64) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "account_id", "IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereAccountIdNotIn(value []uint64) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "account_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) OrderByAccountId(asc bool) *accountHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "account_id "+order)
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereOperateType(p mysql.Predicate, value string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operate_type", p),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereOperateTypeIn(value []string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operate_type", "IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereOperateTypeNotIn(value []string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operate_type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) OrderByOperateType(asc bool) *accountHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "operate_type "+order)
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereOperateTimestamp(p mysql.Predicate, value uint64) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operate_timestamp", p),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereOperateTimestampIn(value []uint64) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operate_timestamp", "IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereOperateTimestampNotIn(value []uint64) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operate_timestamp", "NOT IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) OrderByOperateTimestamp(asc bool) *accountHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "operate_timestamp "+order)
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereContent(p mysql.Predicate, value string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "content", p),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereContentIn(value []string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "content", "IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereContentNotIn(value []string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "content", "NOT IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) OrderByContent(asc bool) *accountHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "content "+order)
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereOperator(p mysql.Predicate, value string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operator", p),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereOperatorIn(value []string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operator", "IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereOperatorNotIn(value []string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operator", "NOT IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) OrderByOperator(asc bool) *accountHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "operator "+order)
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereOperatorRoleType(p mysql.Predicate, value string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operator_role_type", p),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereOperatorRoleTypeIn(value []string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operator_role_type", "IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereOperatorRoleTypeNotIn(value []string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operator_role_type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) OrderByOperatorRoleType(asc bool) *accountHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "operator_role_type "+order)
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereCreatedTimestamp(p mysql.Predicate, value uint64) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_timestamp", p),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereCreatedTimestampIn(value []uint64) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_timestamp", "IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereCreatedTimestampNotIn(value []uint64) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_timestamp", "NOT IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) OrderByCreatedTimestamp(asc bool) *accountHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_timestamp "+order)
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereModifiedTimestamp(p mysql.Predicate, value uint64) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "modified_timestamp", p),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereModifiedTimestampIn(value []uint64) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "modified_timestamp", "IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereModifiedTimestampNotIn(value []uint64) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "modified_timestamp", "NOT IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) OrderByModifiedTimestamp(asc bool) *accountHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "modified_timestamp "+order)
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereCreatedUser(p mysql.Predicate, value string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_user", p),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereCreatedUserIn(value []string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_user", "IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereCreatedUserNotIn(value []string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_user", "NOT IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) OrderByCreatedUser(asc bool) *accountHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_user "+order)
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereUpdatedUser(p mysql.Predicate, value string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_user", p),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereUpdatedUserIn(value []string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_user", "IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) WhereUpdatedUserNotIn(value []string) *accountHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_user", "NOT IN"),
		value,
	})
	return qb
}

func (qb *accountHistoryQueryBuilder) OrderByUpdatedUser(asc bool) *accountHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "updated_user "+order)
	return qb
}
