mysql = {}

[mysql.read]
addr = "<tencent-cloud-mysql-host>:<port>"   # e.g. cdb-xxxx.tencentcdb.com:3306
user = "<username>"
pass = "<password>"
name = "<database>"

[mysql.write]
addr = "<tencent-cloud-mysql-host>:<port>"
user = "<username>"
pass = "<password>"
name = "<database>"

[mysql.base]
maxOpenConn = 50
maxIdleConn = 10
connMaxLifeTime = 30

[redis]
addr = "127.0.0.1:6379"
pass = ""
db = 0
maxRetries = 3
poolSize = 20
minIdleConns = 5

[mail]
host = "smtp.example.com"
port = 465
user = "no-reply@example.com"
pass = "******"
to   = "admin@example.com"

[hashids]
secret = "replace-with-your-secret"
length = 8

[language]
local = "zh-cn"

[hashids]
  length = 12
  secret = "6ab6122836cfef95f8db"

[language]
  local = "zh-cn"

[mail]
  host = "smtp.163.com"
  pass = ""
  port = 465
  to = ""
  user = ""

[mysql]

  [mysql.base]
    connmaxlifetime = 60
    maxidleconn = 60
    maxopenconn = 10

  [mysql.read]
    addr = "gz-cdb-pepynap7.sql.tencentcdb.com:63623"
    name = "marriage_system"
    pass = "19970901Zyt"
    user = "marriage_system"

  [mysql.write]
    addr = "gz-cdb-pepynap7.sql.tencentcdb.com:63623"
    name = "marriage_system"
    pass = "19970901Zyt"
    user = "marriage_system"

[redis]
  addr = "127.0.0.1:6379"
  db = "0"
  maxretries = 3
  minidleconns = 20
  pass = ""
  poolsize = 50 