// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://github.com/xinliangnote/go-gin-api/blob/master/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/account-histories": {
            "get": {
                "description": "分页获取账户操作历史记录",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "获取账户历史记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "账户ID",
                        "name": "accountId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "账户用户名",
                        "name": "accountUsername",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "当前页码",
                        "name": "current",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.historiesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    }
                }
            }
        },
        "/api/v1/accounts": {
            "get": {
                "description": "分页获取账户列表，支持搜索和筛选",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "获取账户列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "当前页码",
                        "name": "current",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户名搜索",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "姓名搜索",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "角色类型筛选",
                        "name": "roleType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态筛选",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "手机号搜索",
                        "name": "phone",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "所属组筛选",
                        "name": "belongGroup",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "所属团队筛选",
                        "name": "belongTeam",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "true",
                        "description": "是否包含组信息",
                        "name": "includeGroup",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "true",
                        "description": "是否包含团队信息",
                        "name": "includeTeam",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.listResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    }
                }
            },
            "post": {
                "description": "创建新账户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "创建账户",
                "parameters": [
                    {
                        "description": "创建账户请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.createRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.createResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    }
                }
            }
        },
        "/api/v1/accounts/{accountId}": {
            "get": {
                "description": "根据账户ID获取详细信息",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "获取账户详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "账户ID",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "true",
                        "description": "是否包含组信息",
                        "name": "includeGroup",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "true",
                        "description": "是否包含团队信息",
                        "name": "includeTeam",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.detailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    }
                }
            },
            "put": {
                "description": "更新账户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "更新账户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "账户ID",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新账户请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.updateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.updateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    }
                }
            }
        },
        "/api/v1/analytics/account/rankings": {
            "get": {
                "description": "按开单或留资获取个人排名",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "获取个人排名数据",
                "parameters": [
                    {
                        "enum": [
                            "paid_count",
                            "lead_count"
                        ],
                        "type": "string",
                        "description": "指标类型",
                        "name": "metric",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "today",
                            "week",
                            "last7days",
                            "month"
                        ],
                        "type": "string",
                        "default": "month",
                        "description": "时间范围",
                        "name": "time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "返回前N名",
                        "name": "top",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "归属组ID",
                        "name": "belongGroupId",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "total",
                            "name"
                        ],
                        "type": "string",
                        "description": "排序字段",
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "排序方向",
                        "name": "sortOrder",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/analytics.accountRankingsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    }
                }
            }
        },
        "/api/v1/analytics/account/trends": {
            "get": {
                "description": "返回个人在开单或留资方面的趋势数据",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "获取个人趋势数据",
                "parameters": [
                    {
                        "enum": [
                            "paid_count",
                            "lead_count"
                        ],
                        "type": "string",
                        "description": "指标类型",
                        "name": "metric",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "today",
                            "week",
                            "last7days",
                            "month"
                        ],
                        "type": "string",
                        "default": "month",
                        "description": "时间范围",
                        "name": "time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "返回前N名",
                        "name": "top",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "归属组ID",
                        "name": "belongGroupId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/analytics.accountTrendsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    }
                }
            }
        },
        "/api/v1/analytics/customer-authorization-record/composition": {
            "get": {
                "description": "返回按多个维度的客资构成占比",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "获取客资授权记录构成（包含城市分布）",
                "parameters": [
                    {
                        "enum": [
                            "today",
                            "week",
                            "last7days",
                            "month"
                        ],
                        "type": "string",
                        "default": "month",
                        "description": "统计时间范围",
                        "name": "time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "归属组ID",
                        "name": "belongGroupId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/analytics.customerCompositionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    }
                }
            }
        },
        "/api/v1/analytics/teams/rankings": {
            "get": {
                "description": "按开单或留资对团队进行排名",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "获取团队排名（全体团队维度）",
                "parameters": [
                    {
                        "enum": [
                            "paid_count",
                            "lead_count"
                        ],
                        "type": "string",
                        "default": "paid_count",
                        "description": "指标",
                        "name": "metric",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "today",
                            "week",
                            "last7days",
                            "month"
                        ],
                        "type": "string",
                        "default": "month",
                        "description": "时间范围",
                        "name": "time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "返回前N名",
                        "name": "top",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/analytics.teamRankingsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    }
                }
            }
        },
        "/api/v1/analytics/teams/trends": {
            "get": {
                "description": "返回多支团队在时间范围内的趋势",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "获取团队多序列趋势（多队折线）",
                "parameters": [
                    {
                        "enum": [
                            "paid_count",
                            "lead_count"
                        ],
                        "type": "string",
                        "default": "paid_count",
                        "description": "指标",
                        "name": "metric",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "today",
                            "week",
                            "last7days",
                            "month"
                        ],
                        "type": "string",
                        "default": "month",
                        "description": "时间范围",
                        "name": "time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "返回前N条折线",
                        "name": "top",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/analytics.teamsTrendsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "用户登录接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CoreAuth"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.loginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "description": "用户退出登录",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CoreAuth"
                ],
                "summary": "退出登录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.logoutResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    }
                }
            }
        },
        "/api/v1/customer-authorization-records": {
            "get": {
                "description": "分页获取客户授权记录列表，支持搜索和筛选",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "获取客户授权记录列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "当前页码",
                        "name": "current",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "姓名搜索",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "城市搜索",
                        "name": "city",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "手机号搜索",
                        "name": "phone",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "归属组搜索",
                        "name": "group",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "归属团队搜索",
                        "name": "team",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "归属账户搜索",
                        "name": "account",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "是否已授权筛选",
                        "name": "isAuthorized",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "是否已买单筛选",
                        "name": "isPaid",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "出生年份最小值",
                        "name": "birthYearMin",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "出生年份最大值",
                        "name": "birthYearMax",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "收入最小值",
                        "name": "incomeMin",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "收入最大值",
                        "name": "incomeMax",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/customer_authorization_record.listResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的客户授权记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "创建客户授权记录",
                "parameters": [
                    {
                        "description": "客户授权记录信息",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/customer_authorization_record.createRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/customer_authorization_record.createResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    }
                }
            }
        },
        "/api/v1/customer-authorization-records/check-phone": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "检查手机号是否已存在",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/customer_authorization_record.checkPhoneResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/customer-authorization-records/{id}": {
            "get": {
                "description": "根据ID获取客户授权记录详情",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "获取客户授权记录详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "客户授权记录ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/customer_authorization_record.detailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    }
                }
            },
            "put": {
                "description": "根据ID更新客户授权记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "更新客户授权记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "客户授权记录ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "客户授权记录更新信息",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/customer_authorization_record.updateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/customer_authorization_record.updateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    }
                }
            }
        },
        "/api/v1/me": {
            "get": {
                "description": "获取当前登录用户的详细信息",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CoreAuth"
                ],
                "summary": "获取当前用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.detailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/code.Failure"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "account.accountData": {
            "type": "object",
            "properties": {
                "belongGroup": {
                    "description": "所属组",
                    "allOf": [
                        {
                            "$ref": "#/definitions/account.org"
                        }
                    ]
                },
                "belongTeam": {
                    "description": "所属团队",
                    "allOf": [
                        {
                            "$ref": "#/definitions/account.org"
                        }
                    ]
                },
                "createdAt": {
                    "description": "创建时间戳",
                    "type": "integer"
                },
                "id": {
                    "description": "账户ID",
                    "type": "string"
                },
                "lastLoginAt": {
                    "description": "最后登录时间戳",
                    "type": "integer"
                },
                "name": {
                    "description": "姓名",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "roleType": {
                    "description": "角色类型",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "修改时间戳",
                    "type": "integer"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "account.accountHistoryData": {
            "type": "object",
            "properties": {
                "accountId": {
                    "description": "账户ID",
                    "type": "string"
                },
                "content": {
                    "description": "操作内容",
                    "type": "object",
                    "additionalProperties": true
                },
                "id": {
                    "description": "历史记录ID",
                    "type": "string"
                },
                "operateType": {
                    "description": "操作类型",
                    "type": "string"
                },
                "operatedAt": {
                    "description": "操作时间戳",
                    "type": "integer"
                },
                "operatorRoleType": {
                    "description": "操作人角色类型",
                    "type": "string"
                },
                "operator_name": {
                    "description": "操作人姓名",
                    "type": "string"
                },
                "operator_username": {
                    "description": "操作人用户名",
                    "type": "string"
                }
            }
        },
        "account.createRequest": {
            "type": "object",
            "required": [
                "name",
                "password",
                "username"
            ],
            "properties": {
                "belongGroup": {
                    "description": "所属组",
                    "type": "string"
                },
                "name": {
                    "description": "姓名",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "roleType": {
                    "description": "角色类型",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "account.createResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/account.accountData"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "account.detailResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/account.accountData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "account.historiesResponse": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/account.accountHistoryData"
                    }
                },
                "pageSize": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "account.listResponse": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/account.accountData"
                    }
                },
                "pageSize": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "account.loginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "account.loginResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "token": {
                            "type": "string"
                        },
                        "username": {
                            "type": "string"
                        }
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "account.logoutResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "account.org": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "创建时间戳",
                    "type": "integer"
                },
                "currentCnt": {
                    "description": "当前成员数量",
                    "type": "integer"
                },
                "id": {
                    "description": "组织ID",
                    "type": "integer"
                },
                "name": {
                    "description": "组织名称",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "修改时间戳",
                    "type": "integer"
                },
                "username": {
                    "description": "组织用户名",
                    "type": "string"
                }
            }
        },
        "account.updateRequest": {
            "type": "object",
            "required": [
                "accountID"
            ],
            "properties": {
                "accountID": {
                    "description": "账户ID",
                    "type": "string"
                },
                "belongGroup": {
                    "description": "所属组",
                    "type": "string"
                },
                "belongTeam": {
                    "description": "所属团队",
                    "type": "string"
                },
                "name": {
                    "description": "姓名",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "string"
                }
            }
        },
        "account.updateResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "analytics.accountRankingsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "meta": {
                            "$ref": "#/definitions/analytics.analyticsMeta"
                        },
                        "rankings": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/analytics.rankingItem"
                            }
                        }
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "analytics.accountTrendSeries": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "trends": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analytics.trendPoint"
                    }
                }
            }
        },
        "analytics.accountTrendsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "meta": {
                            "$ref": "#/definitions/analytics.analyticsMeta"
                        },
                        "trends": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/analytics.accountTrendSeries"
                            }
                        }
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "analytics.analyticsMeta": {
            "type": "object",
            "properties": {
                "averageValue": {
                    "type": "number"
                },
                "belongGroupId": {
                    "type": "string"
                },
                "dateRange": {
                    "$ref": "#/definitions/analytics.dateSpan"
                },
                "metric": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "totalTeams": {
                    "type": "integer"
                },
                "totalUsers": {
                    "type": "integer"
                }
            }
        },
        "analytics.customerComposition": {
            "type": "object",
            "properties": {
                "birthYear": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analytics.distributionItem"
                    }
                },
                "city": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analytics.distributionItem"
                    }
                },
                "education": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analytics.distributionItem"
                    }
                },
                "gender": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analytics.distributionItem"
                    }
                },
                "income": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analytics.distributionItem"
                    }
                },
                "store": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analytics.distributionItem"
                    }
                }
            }
        },
        "analytics.customerCompositionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "compositions": {
                            "$ref": "#/definitions/analytics.customerComposition"
                        },
                        "meta": {
                            "type": "object",
                            "properties": {
                                "belongGroupId": {
                                    "type": "string"
                                },
                                "total": {
                                    "type": "number"
                                }
                            }
                        }
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "analytics.dateSpan": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                }
            }
        },
        "analytics.distributionItem": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "analytics.rankingItem": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "rankChange": {
                    "type": "integer"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "analytics.teamRankingsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "meta": {
                            "$ref": "#/definitions/analytics.analyticsMeta"
                        },
                        "rankings": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/analytics.rankingItem"
                            }
                        }
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "analytics.teamTrendSeries": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "teamId": {
                    "type": "string"
                },
                "trends": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analytics.trendPoint"
                    }
                }
            }
        },
        "analytics.teamsTrendsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "meta": {
                            "$ref": "#/definitions/analytics.analyticsMeta"
                        },
                        "trends": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/analytics.teamTrendSeries"
                            }
                        }
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "analytics.trendPoint": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                }
            }
        },
        "code.Failure": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务码",
                    "type": "integer"
                },
                "message": {
                    "description": "描述信息",
                    "type": "string"
                }
            }
        },
        "customer_authorization_record.checkPhoneResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/customer_authorization_record.customerData"
                },
                "exists": {
                    "type": "boolean"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "customer_authorization_record.createRequest": {
            "type": "object",
            "properties": {
                "assignmentStatus": {
                    "description": "assigned/unassigned",
                    "type": "string"
                },
                "authorizationPhotos": {
                    "description": "授权照片",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "authorizationStatus": {
                    "description": "authorized/unauthorized",
                    "type": "string"
                },
                "authorizedStoreId": {
                    "description": "授权门店ID",
                    "type": "string"
                },
                "belongAccountId": {
                    "description": "归属账户ID",
                    "type": "string"
                },
                "belongTeamId": {
                    "description": "归属小队ID",
                    "type": "string"
                },
                "birthYear": {
                    "description": "出生年份",
                    "type": "integer"
                },
                "city": {
                    "description": "城市ID",
                    "type": "string"
                },
                "completionStatus": {
                    "description": "complete/incomplete",
                    "type": "string"
                },
                "drainageAccount": {
                    "description": "引流账户",
                    "type": "string"
                },
                "drainageChannel": {
                    "description": "引流渠道",
                    "type": "string"
                },
                "drainageId": {
                    "description": "引流ID",
                    "type": "string"
                },
                "education": {
                    "description": "学历",
                    "type": "string"
                },
                "gender": {
                    "description": "male/female",
                    "type": "string"
                },
                "height": {
                    "description": "身高",
                    "type": "integer"
                },
                "income": {
                    "description": "收入（万）",
                    "type": "integer"
                },
                "name": {
                    "description": "用户称呼/姓名",
                    "type": "string"
                },
                "paymentAmount": {
                    "description": "支付金额",
                    "type": "number"
                },
                "paymentStatus": {
                    "description": "paid/unpaid",
                    "type": "string"
                },
                "phone": {
                    "description": "11位手机号",
                    "type": "string"
                },
                "profession": {
                    "description": "职业",
                    "type": "string"
                },
                "refundAmount": {
                    "description": "退款金额",
                    "type": "number"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "wechat": {
                    "description": "微信",
                    "type": "string"
                }
            }
        },
        "customer_authorization_record.createResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/customer_authorization_record.customerData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "customer_authorization_record.customerData": {
            "type": "object",
            "properties": {
                "assignmentStatus": {
                    "description": "分配状态",
                    "type": "string"
                },
                "authStore": {
                    "description": "授权门店名称（展示用）",
                    "type": "string"
                },
                "authorizationPhotos": {
                    "description": "授权照片",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "authorizationStatus": {
                    "description": "授权状态",
                    "type": "string"
                },
                "belongAccount": {
                    "description": "归属账户",
                    "allOf": [
                        {
                            "$ref": "#/definitions/customer_authorization_record.refObject"
                        }
                    ]
                },
                "belongGroup": {
                    "description": "归属组",
                    "allOf": [
                        {
                            "$ref": "#/definitions/customer_authorization_record.refObject"
                        }
                    ]
                },
                "belongTeam": {
                    "description": "归属小队",
                    "allOf": [
                        {
                            "$ref": "#/definitions/customer_authorization_record.refObject"
                        }
                    ]
                },
                "birthYear": {
                    "description": "出生年份",
                    "type": "integer"
                },
                "city": {
                    "description": "城市ID",
                    "type": "string"
                },
                "completionStatus": {
                    "description": "完善状态",
                    "type": "string"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "drainageAccount": {
                    "description": "引流账户",
                    "type": "string"
                },
                "drainageChannel": {
                    "description": "引流渠道",
                    "type": "string"
                },
                "drainageId": {
                    "description": "引流ID",
                    "type": "string"
                },
                "education": {
                    "description": "学历",
                    "type": "string"
                },
                "gender": {
                    "description": "性别",
                    "type": "string"
                },
                "height": {
                    "description": "身高(cm)",
                    "type": "integer"
                },
                "income": {
                    "description": "收入（万）",
                    "type": "integer"
                },
                "key": {
                    "description": "记录ID",
                    "type": "integer"
                },
                "name": {
                    "description": "客户姓名",
                    "type": "string"
                },
                "paymentAmount": {
                    "description": "支付金额",
                    "type": "number"
                },
                "paymentStatus": {
                    "description": "付费状态",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号（可脱敏）",
                    "type": "string"
                },
                "profession": {
                    "description": "职业",
                    "type": "string"
                },
                "refundAmount": {
                    "description": "退款金额",
                    "type": "number"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "修改时间",
                    "type": "string"
                },
                "wechat": {
                    "description": "微信号",
                    "type": "string"
                }
            }
        },
        "customer_authorization_record.detailResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/customer_authorization_record.customerData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "customer_authorization_record.listMeta": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "customer_authorization_record.listResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/customer_authorization_record.customerData"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/customer_authorization_record.listMeta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "customer_authorization_record.refObject": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "customer_authorization_record.updateRequest": {
            "type": "object",
            "properties": {
                "assignmentStatus": {
                    "type": "string"
                },
                "authorizationPhotos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "authorizationStatus": {
                    "type": "string"
                },
                "birthYear": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "completionStatus": {
                    "type": "string"
                },
                "drainageAccount": {
                    "type": "string"
                },
                "drainageChannel": {
                    "type": "string"
                },
                "drainageId": {
                    "type": "string"
                },
                "education": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "income": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "paymentAmount": {
                    "type": "number"
                },
                "paymentStatus": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "profession": {
                    "type": "string"
                },
                "refundAmount": {
                    "type": "number"
                },
                "remark": {
                    "type": "string"
                },
                "wechat": {
                    "type": "string"
                }
            }
        },
        "customer_authorization_record.updateResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/customer_authorization_record.customerData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "LoginToken": {
            "type": "apiKey",
            "name": "token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "swagger 接口文档",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
